//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniso.InStat.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uniso.InStat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajax_loader2 {
            get {
                object obj = ResourceManager.GetObject("ajax_loader2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 900100	9	1		Прочее
        ///900200	9	2		Толчок соперника на борт
        ///900300	9	3		Неправильная атака
        ///900400	9	4		Грубость
        ///900500	9	5		Игра высоко поднятой клюшкой
        ///900600	9	6		Задержка руками/клюшкой
        ///900700	9	7		Атака Игрока, не владеющего шайбой (блокировка)
        ///900800	9	8		Нарушение численного состава
        ///900900	9	9		Удар (клюшкой, локтем, ногой головой)
        ///901000	9	10		Подножка
        ///901100	9	11		Сдвиг ворот
        ///901200	9	12		Неспортивное поведение
        ///901300	9	13		Драка
        ///901400	9	14		Выброс шайбы.
        /// </summary>
        internal static string foul_marker_rules {
            get {
                return ResourceManager.GetString("foul_marker_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,	,	action_id,	action_type,	win,	name,	name_eng,	player,	opponent,	point,	dest,	stop time,	Доп,	Описание,	order,	,	,	,	,	
        ///,	100000,	,	,	,	Передачи,	,	,	,	,	,	,	,	,	,	,	,	,	,	
        ///x,	100100,	1,	1,	,	Вбрасывание,	Faceoff,	v,	v,	v,	,	,	,	,	,	,	
        ///x,	100200,	1,	2,	,	Голевая передача,	assist,	v,	v,	v,	,	,	,	,	,	,	,	,	,	
        ///x,	100300,	1,	3,	,	Пас по борту,	,	v,	v,	v,	v,	,	,	Пас по борту,	,	,	,	,	,	
        ///x,	100301,	1,	3,	1,	Пас по борту (+),	,	v,	v,	v,	v,	,	,	Пас по борту точный,	,	,	,	,	,	
        ///x,	100302,	1,	3,	2,	Пас по борт [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string marker_rules {
            get {
                return ResourceManager.GetString("marker_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user2 {
            get {
                object obj = ResourceManager.GetObject("user2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
