//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniso.InStat.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uniso.InStat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajax_loader2 {
            get {
                object obj = ResourceManager.GetObject("ajax_loader2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1		Прочее												p0	p1	p2	t0	t1
        ///2		Толчок соперника на борт									p2		t1
        ///3		Неправильная атака											p2		t1
        ///4		Грубость												p1	p2		t1
        ///5		Игра высоко поднятой клюшкой								p2		t1
        ///6		Задержка руками/клюшкой										p2		t1
        ///7		Атака Игрока, не владеющего шайбой (блокировка)				p2		t1
        ///8		Нарушение численного состава						p0			t0	
        ///9		Удар (клюшкой, локтем, ногой головой)						p2		t1
        ///10		Подножка													p2		t1
        ///11		Сдвиг ворот												p1			t1
        ///12		Неспортивное поведение								 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string foul_marker_rules {
            get {
                return ResourceManager.GetString("foul_marker_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoalKeeperBody {
            get {
                object obj = ResourceManager.GetObject("GoalKeeperBody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goalkeeperstate {
            get {
                object obj = ResourceManager.GetObject("goalkeeperstate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HockeyGateway {
            get {
                object obj = ResourceManager.GetObject("HockeyGateway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,	,	action_id,	action_type,	win,	name,	name_eng,	player,	opponent,	point,	dest,	stop time,	Доп,	Описание,	order,	,	,	,	,	
        ///,	100000,	,	,	,	Передачи,	,	,	,	,	,	,	,	,	,	,	,	,	,	
        ///x,	100100,	1,	1,	,	Вбрасывание,	Faceoff,	v,	v,	v,	,	,	,	,	,	,	
        ///x,	100200,	1,	2,	,	Голевая передача,	assist,	v,	v,	v,	,	,	,	,	,	,	,	,	,	
        ///x,	100300,	1,	3,	,	Пас по борту,	,	v,	v,	v,	v,	,	,	Пас по борту,	,	,	,	,	,	
        ///x,	100301,	1,	3,	1,	Пас по борту (+),	,	v,	v,	v,	v,	,	,	Пас по борту точный,	,	,	,	,	,	
        ///x,	100302,	1,	3,	2,	Пас по борт [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string marker_rules {
            get {
                return ResourceManager.GetString("marker_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7															СВОЙСТВА (c_match_event_prop)						СВЯЗИ (c_match_event_prop_values)				
        ///	action_code	name	name_eng	action_id	action_type	win	player	opponent	point	dest	stop time	Описание			Property_ID	Свойства(типы)	Описание	Маркеры	описание		Property_ID	Value_ID	Свойства(значения)	Описание	
        ///	100000	Передачи													1	Тип Броска	Тип Броска	все 4,8		INSERT INTO c_match_event_prop(id,name,descr) SELECT 1, &apos;Тип Броска&apos;, &apos;Тип Броска&apos;;	1	1	Щелчок	401000	INSERT INTO c_match_event_prop_values(c_match_event_ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NewMarkersProperties {
            get {
                return ResourceManager.GetString("NewMarkersProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user2 {
            get {
                object obj = ResourceManager.GetObject("user2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
